# Generated by Django 2.2.24 on 2021-06-14 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
